package routes

import (
	"github.com/gin-gonic/gin"
	"github.com/lucasjct/controllers"
	_ "github.com/lucasjct/docs"               // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

func HandleRequest() {
	r := gin.Default()
	r.GET("/artist", controllers.ShowAllArtist)
	r.GET("/artist/specific", controllers.SearchArtistById)
	r.GET("/artist/name", controllers.SearchArtistByName)
	r.GET("/ping", controllers.Ping)
	r.DELETE("/artist", controllers.DeleteArtist)
	r.POST("/artist", controllers.CreateNewArtist)
	r.PATCH("/artist", controllers.UpdateArtist)
	r.NoRoute(controllers.RouteNotFound) // use it when the return will be not found
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run()
}
