definitions:
  models.Artist:
    type: object
info:
  contact: {}
paths:
  /artist:
    get:
      responses:
        "200":
          description: OK
      summary: List all artist
      tags:
      - Artists
    post:
      consumes:
      - application/json
      description: This endpoint allows the creation of a new artist by providing
        artist details in JSON format.
      parameters:
      - description: Artist details
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/models.Artist'
      produces:
      - application/json
      responses:
        "201":
          description: Artist Created Successfully
          schema:
            $ref: '#/definitions/models.Artist'
      summary: Create a new artist
      tags:
      - Artists
  /artist/{id}:
    delete:
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete a specific artist
      tags:
      - Artists
    get:
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: List an artist by ID
      tags:
      - Artists
    patch:
      consumes:
      - application/json
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Artist Updated Successfully
          schema:
            $ref: '#/definitions/models.Artist'
      summary: Update a specific artist
      tags:
      - Artists
  /artist/{name}:
    get:
      parameters:
      - description: Artist Name
        in: path
        name: name
        required: true
        type: string
      - description: Artist details
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/models.Artist'
      responses:
        "200":
          description: Artist object
          schema:
            $ref: '#/definitions/models.Artist'
      summary: Search artist by name
      tags:
      - Artists
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Test API connection
      tags:
      - Test API connection
swagger: "2.0"
