definitions:
  models.Artist:
    properties:
      album:
        type: string
      country:
        type: string
      name:
        type: string
      released:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /artist:
    delete:
      parameters:
      - description: ID of the artist
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete a specific artist
      tags:
      - Artists
    get:
      responses:
        "200":
          description: OK
      summary: List all artist
      tags:
      - Artists
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID of the artist
        in: query
        name: id
        required: true
        type: integer
      - description: Artist details
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/models.Artist'
      produces:
      - application/json
      responses:
        "200":
          description: Artist updated successfully
          schema:
            $ref: '#/definitions/models.Artist'
      summary: Update a specific artist
      tags:
      - Artists
    post:
      consumes:
      - application/json
      parameters:
      - description: Artist details
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/models.Artist'
      - default: 1
        description: Page number
        example: 1
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Artist Created Successfully
          schema:
            $ref: '#/definitions/models.Artist'
      summary: Create a new artist
      tags:
      - Artists
  /artist/name:
    get:
      parameters:
      - description: Name of the artist
        example: '"Emicida"'
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Search artist by name
      tags:
      - Artists
  /artist/specific:
    get:
      parameters:
      - description: ID of the artist
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: List an artist by ID
      tags:
      - Artists
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Test API connection
      tags:
      - Test API connection
swagger: "2.0"
